import type { CollectionAfterChangeHook } from 'payload'
import { generateConfirmationEmail } from '@/email/generateConfirmationEmail'

export const handleNewsletterSubmission: CollectionAfterChangeHook = async ({
  doc,
  operation,
  req,
}) => {
  if (operation !== 'create') return doc

  // Resolve the form — could be a populated object or just an ID
  const form = typeof doc.form === 'object' ? doc.form : await req.payload.findByID({
    collection: 'forms',
    id: doc.form,
    depth: 0,
  })

  // Only process newsletter forms (title must contain "newsletter", case-insensitive)
  if (!form?.title?.toLowerCase().includes('newsletter')) return doc

  // Extract email from submission data
  const emailField = doc.submissionData?.find(
    (field: { field: string; value: unknown }) => field.field === 'email',
  )
  const email = emailField?.value as string | undefined

  if (!email) return doc

  // Detect locale from the submission (if a locale field exists) or default to 'en'
  const localeField = doc.submissionData?.find(
    (field: { field: string; value: unknown }) => field.field === 'locale',
  )
  const locale = (localeField?.value as 'en' | 'pl') || 'en'

  try {
    // Check if subscriber already exists
    const existing = await req.payload.find({
      collection: 'subscribers',
      where: { email: { equals: email } },
      limit: 1,
    })

    if (existing.docs.length > 0) {
      const subscriber = existing.docs[0]

      // Already confirmed — skip
      if (subscriber.confirmed) return doc

      // Resend confirmation with existing token
      const baseUrl = process.env.NEXT_PUBLIC_SERVER_URL || 'http://localhost:3000'
      const confirmUrl = `${baseUrl}/api/confirm?token=${subscriber.token}&locale=${locale}`
      const { subject, html } = generateConfirmationEmail({ locale, confirmUrl })

      await req.payload.sendEmail({
        to: email,
        subject,
        html,
      })

      return doc
    }

    // Create new subscriber (token auto-generated by collection hook)
    const subscriber = await req.payload.create({
      collection: 'subscribers',
      data: { email, locale },
    })

    // Send confirmation email
    const baseUrl = process.env.NEXT_PUBLIC_SERVER_URL || 'http://localhost:3000'
    const confirmUrl = `${baseUrl}/api/confirm?token=${subscriber.token}&locale=${locale}`
    const { subject, html } = generateConfirmationEmail({ locale, confirmUrl })

    await req.payload.sendEmail({
      to: email,
      subject,
      html,
    })
  } catch (error) {
    req.payload.logger.error({ err: error, email }, 'Failed to process newsletter subscription')
  }

  return doc
}
