import { NextRequest } from 'next/server'
import { getPayload } from 'payload'
import config from '@payload-config'
import { generateConfirmationEmail } from '@/email/generateConfirmationEmail'
import { getUnsubscribeUrl } from '@/lib/resend'
import type { Subscriber } from '@/payload-types'

type SubscriberLocale = NonNullable<Subscriber['locale']>

const VALID_LOCALES: SubscriberLocale[] = ['de', 'en', 'es', 'fr', 'it', 'nl', 'pl', 'ru', 'uk']

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type',
}

function json(data: Record<string, unknown>, status = 200) {
  return new Response(JSON.stringify(data), {
    status,
    headers: { 'Content-Type': 'application/json', ...corsHeaders },
  })
}

export async function OPTIONS() {
  return new Response(null, { headers: corsHeaders })
}

export async function POST(request: NextRequest) {
  let body: { email?: string; locale?: string; _hp_company?: string }
  try {
    body = await request.json()
  } catch {
    return json({ error: 'Invalid JSON' }, 400)
  }

  // Honeypot — silently succeed if bot field is filled
  if (body._hp_company) {
    return json({ status: 'created' })
  }

  const email = (body.email || '').trim().toLowerCase()
  if (!email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
    return json({ error: 'Invalid email address' }, 400)
  }

  const locale: SubscriberLocale = VALID_LOCALES.includes(body.locale as SubscriberLocale)
    ? (body.locale as SubscriberLocale)
    : 'en'
  const payload = await getPayload({ config })

  try {
    // Check if subscriber already exists
    const existing = await payload.find({
      collection: 'subscribers',
      where: { email: { equals: email } },
      limit: 1,
    })

    if (existing.docs.length > 0) {
      const subscriber = existing.docs[0]

      if (subscriber.confirmed) {
        return json({ status: 'already-confirmed' })
      }

      // Resend confirmation email
      const baseUrl = process.env.NEXT_PUBLIC_SERVER_URL || 'http://localhost:3000'
      const confirmUrl = `${baseUrl}/api/confirm?token=${subscriber.token}`
      const unsubscribeUrl = getUnsubscribeUrl(subscriber.token!)
      const { subject, html } = generateConfirmationEmail({
        locale: locale as 'en' | 'pl',
        confirmUrl,
        unsubscribeUrl,
      })

      await payload.sendEmail({
        to: email,
        subject,
        html,
        headers: {
          'List-Unsubscribe': `<${unsubscribeUrl}>`,
          'List-Unsubscribe-Post': 'List-Unsubscribe=One-Click',
        },
      })

      return json({ status: 'resent' })
    }

    // Create new subscriber (token auto-generated by collection hook)
    const subscriber = await payload.create({
      collection: 'subscribers',
      draft: false,
      data: { email, locale },
    })

    // Send confirmation email
    const baseUrl = process.env.NEXT_PUBLIC_SERVER_URL || 'http://localhost:3000'
    const confirmUrl = `${baseUrl}/api/confirm?token=${subscriber.token}`
    const unsubscribeUrl = getUnsubscribeUrl(subscriber.token!)
    const { subject, html } = generateConfirmationEmail({
      locale: locale as 'en' | 'pl',
      confirmUrl,
      unsubscribeUrl,
    })

    await payload.sendEmail({
      to: email,
      subject,
      html,
      headers: {
        'List-Unsubscribe': `<${unsubscribeUrl}>`,
        'List-Unsubscribe-Post': 'List-Unsubscribe=One-Click',
      },
    })

    return json({ status: 'created' })
  } catch (error) {
    payload.logger.error({ err: error, email }, 'Failed to process subscription')
    return json({ error: 'Internal error' }, 500)
  }
}
