/**
 * Creates the FAQ page via Payload Local API with the full 45-question layout.
 * Reads layout from /tmp/faq-layout.json (generated by scripts/generate-faq-layout.py).
 *
 * Usage:
 *   python3 scripts/generate-faq-layout.py   # generate layout JSON first
 *   npx tsx scripts/create-faq-page.ts        # create the page
 */

import { readFileSync } from 'fs'

// Load .env before importing Payload (ESM hoists static imports)
const envContent = readFileSync('.env', 'utf-8')
for (const line of envContent.split('\n')) {
  const match = line.match(/^([^#=]+)=(.*)$/)
  if (match) process.env[match[1].trim()] = match[2].trim()
}

async function main() {
  const layoutJson = readFileSync('/tmp/faq-layout.json', 'utf-8')
  const layout = JSON.parse(layoutJson)

  console.log(`Layout: ${layout.length} blocks`)
  let totalQs = 0
  for (const block of layout) {
    if (block.blockType === 'accordion') {
      totalQs += block.accordionItems.length
    }
  }
  console.log(`Total FAQ questions: ${totalQs}`)

  // Dynamic imports so env vars are set first
  const { getPayload } = await import('payload')
  const configPromise = (await import('@payload-config')).default

  const payload = await getPayload({ config: configPromise })

  const page = await payload.create({
    collection: 'pages',
    locale: 'en',
    data: {
      title: 'FAQ',
      slug: 'faq',
      slugLock: false,
      _status: 'published',
      hero: {
        type: 'lowImpact',
        richText: {
          root: {
            children: [
              {
                children: [
                  { detail: 0, format: 0, mode: 'normal', style: '', text: 'Auschwitz FAQ: Answers to the Most Common Visitor Questions', type: 'text', version: 1 },
                ],
                direction: 'ltr', format: '', indent: 0, type: 'heading', version: 1, tag: 'h1',
              },
              { children: [], direction: null, format: '', indent: 0, type: 'paragraph', version: 1, textFormat: 0, textStyle: '' },
            ],
            direction: null, format: '', indent: 0, type: 'root', version: 1,
          },
        },
      },
      meta: {
        title: 'Auschwitz FAQ — Visitor Questions Answered',
        description: 'Answers to frequently asked questions about visiting Auschwitz-Birkenau. Tickets, transport, tours, rules, dress code, opening hours — by a licensed guide since 2006.',
      },
      layout,
    },
  })

  console.log(`\nPage created: id=${page.id}, slug=${page.slug}, status=${page._status}`)
  console.log('Done.')

  process.exit(0)
}

main().catch((err) => {
  console.error('Failed:', err)
  process.exit(1)
})
