/**
 * Creates the "Before You Go — Preparation Checklist" page via Payload Local API.
 * Reads layout from /tmp/checklist-layout.json (generated by scripts/generate-checklist-layout.py).
 *
 * Usage:
 *   python3 scripts/generate-checklist-layout.py   # generate layout JSON first
 *   npx tsx scripts/create-checklist-page.ts        # create the page
 */

import { readFileSync } from 'fs'

// Load .env before importing Payload (ESM hoists static imports)
const envContent = readFileSync('.env', 'utf-8')
for (const line of envContent.split('\n')) {
  const match = line.match(/^([^#=]+)=(.*)$/)
  if (match) process.env[match[1].trim()] = match[2].trim()
}

async function main() {
  const layoutJson = readFileSync('/tmp/checklist-layout.json', 'utf-8')
  const layout = JSON.parse(layoutJson)

  console.log(`Layout: ${layout.length} blocks`)

  const { getPayload } = await import('payload')
  const configPromise = (await import('@payload-config')).default

  const payload = await getPayload({ config: configPromise })

  const page = await payload.create({
    collection: 'pages',
    locale: 'en',
    data: {
      title: 'Before You Go — Auschwitz Visit Checklist',
      slug: 'checklist',
      slugLock: false,
      _status: 'draft',
      hero: {
        type: 'lowImpact',
        richText: {
          root: {
            children: [
              {
                children: [
                  {
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Before You Go — Auschwitz Visit Checklist',
                    type: 'text',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                type: 'heading',
                version: 1,
                tag: 'h1',
              },
              {
                children: [],
                direction: null,
                format: '',
                indent: 0,
                type: 'paragraph',
                version: 1,
                textFormat: 0,
                textStyle: '',
              },
            ],
            direction: null,
            format: '',
            indent: 0,
            type: 'root',
            version: 1,
          },
        },
      },
      meta: {
        title: 'Auschwitz Visit Checklist: What to Pack & Know',
        description:
          'Printable preparation checklist for visiting Auschwitz-Birkenau. Covers booking, transport from Krakow, what to pack, rules, and essential visitor tips.',
      },
      layout,
    },
  })

  console.log(`\nPage created: id=${page.id}, slug=${page.slug}, status=${page._status}`)
  console.log('Done.')

  process.exit(0)
}

main().catch((err) => {
  console.error('Failed:', err)
  process.exit(1)
})
